// SPDX-License-Identifier: GPL-3.0-or-later
//! Built-in stages.
pub mod asset_load;
pub mod audio;
pub mod client_flythrough;
pub mod client_fx;
pub mod client_hud;
pub mod client_ingame_menu;
pub mod client_input;
pub mod client_leave;
pub mod client_load;
pub mod client_match;
pub mod client_menu_match;
pub mod client_models;
pub mod client_session;
pub mod client_ui;
pub mod net_killcam;
pub mod net_loopback;
pub mod net_match;
pub mod net_ui;
pub mod selftest;
pub mod server;
pub mod web_client;
