// SPDX-License-Identifier: GPL-3.0-or-later
//! Built-in stages.
pub mod asset_load;
pub mod audio;
pub mod client_flythrough;
pub mod client_input;
pub mod client_match;
pub mod client_models;
pub mod client_ui;
pub mod net_killcam;
pub mod net_loopback;
pub mod net_match;
pub mod net_ui;
pub mod selftest;
pub mod server;
