[package]
name = "sm3"
description = "D3D9 SM3 bytecode to WGSL translation."
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]

[dev-dependencies]
flate2 = "1"
naga = { version = "30.0.1", features = ["wgsl-in", "wgsl-out"] }

[lints]
workspace = true
