#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerate crates/assets/src/iwi/wavelet_codes.rs from an original iw3mp.exe (1.7).

The engine keeps three 4096-entry prefix-code lookup tables ({i16 value, i16 bits},
indexed by the next 12 stream bits, LSB first). Each distinct (value, bits, code)
triple is emitted; the loader rebuilds the lookup. Usage: gen-wavelet-tables.py iw3mp.exe
"""
import struct, sys

TABLES = [("BLUE", 0x6A1E08), ("RED_GREEN", 0x6A5E08), ("ALPHA", 0x6A9E08)]

exe = open(sys.argv[1], "rb").read()
pe = struct.unpack_from("<I", exe, 0x3C)[0]
nsec, = struct.unpack_from("<H", exe, pe + 6)
optsz, = struct.unpack_from("<H", exe, pe + 20)
base, = struct.unpack_from("<I", exe, pe + 24 + 28)
secs = []
for i in range(nsec):
    o = pe + 24 + optsz + 40 * i
    vsize, va, rsize, roff = struct.unpack_from("<IIII", exe, o + 8)
    secs.append((va, vsize, roff))

def va_to_off(va):
    rva = va - base
    for sva, vsize, roff in secs:
        if sva <= rva < sva + vsize:
            return roff + rva - sva
    raise SystemExit("unmapped " + hex(va))

out = ["// SPDX-License-Identifier: GPL-3.0-or-later",
       "//! Wavelet prefix codes as (value, bit length, code), code bits read LSB first.",
       "//! Generated by scripts/gen-wavelet-tables.py. Value -32768 is the escape.", ""]
for name, va in TABLES:
    off = va_to_off(va)
    seen = {}
    for idx in range(4096):
        v, b = struct.unpack_from("<hh", exe, off + idx * 4)
        assert 1 <= b <= 12
        code = idx & ((1 << b) - 1)
        seen.setdefault((v, b, code), 0)
        seen[(v, b, code)] += 1
    for (v, b, c), n in seen.items():
        assert n == 1 << (12 - b), "table not a clean prefix code"
    assert sum(seen.values()) == 4096
    ents = sorted(seen, key=lambda t: (t[1], t[2]))
    out.append(f"pub const {name}: &[(i16, u8, u16)] = &[")
    for i in range(0, len(ents), 6):
        out.append("    " + " ".join(f"({v}, {b}, {c})," for v, b, c in ents[i:i+6]))
    out.append("];")
    out.append("")
print("\n".join(out))
