// SPDX-License-Identifier: GPL-3.0-only
//! Authoritative match simulation; no GPU, window, or audio dependencies.

pub mod activate;
pub mod anim;
pub mod archive;
pub mod ban;
pub mod bot;
pub mod bullet;
pub mod client;
pub mod cmd;
pub mod combat;
pub mod content;
pub mod cvar;
pub mod delta;
pub mod fire;
pub mod game;
pub mod gamelog;
pub mod gunmotion;
pub mod items;
pub mod lagcomp;
pub mod link;
pub mod mem;
pub mod missile;
pub mod mover;
pub mod nav;
pub mod netsv;
pub mod playeranim;
pub mod rcon;
pub mod script;
pub mod server;
pub mod tags;
pub mod tempev;
pub mod trigger;
pub mod turret;
pub mod ui;
pub mod vehicle;
pub mod vote;
